#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#define MOTOR_PWM_PERIOD        (1600U)
#define MOTOR_PWM_DEAD_TICKS    (20U)
#define SPEED_CTRL_PERIOD_MS    (20U)
#define UART_REPORT_PERIOD_MS   (100U)
#define PWM_STEP_LIMIT          (30)
#define STARTUP_SAFE_MS         (800U)

#define DEFAULT_TARGET_COUNTS   (120.0f)
#define DEFAULT_KP              (1.20f)
#define DEFAULT_KI              (0.003f)
#define DEFAULT_KD              (0.0f)
#define DEFAULT_MAX_OUTPUT      (390.0f)
#define DEFAULT_MAX_INTEGRAL    (270.0f)

#define DEFAULT_LEFT_PWM_TRIM   (0)
#define DEFAULT_RIGHT_PWM_TRIM  (-14)
#define DEFAULT_BRAKE_MS        (120U)

#define LINE_DEFAULT_KP         (3.80f)
#define LINE_DEFAULT_KD         (2.40f)
#define LINE_DEFAULT_TARGET     (190.0f)
#define LINE_DEFAULT_BASE_PWM   (400)
#define LINE_CORR_LIMIT         (460)
#define LINE_MIN_WHEEL_TARGET   (25.0f)
#define LINE_SEARCH_PWM         (0)
#define LINE_CORRECTION_SIGN    (1)
#define LINE_CURVE_ERR_START    (14)
#define LINE_CURVE_TARGET_DROP  (55.0f)

#define A_MARK_DEFAULT_TOTAL    (3U)
#define A_MARK_DEFAULT_SPAN     (3U)
#define A_MARK_DEFAULT_FRAMES   (2U)
#define A_MARK_FINISH_TOTAL     (3U)
#define A_MARK_FINISH_SPAN      (3U)
#define A_MARK_RELEASE_FRAMES   (4U)
#define A_MARK_MIN_LAP_MS       (5000U)
#define A_MARK_MIN_LAP_COUNTS   (9000U)
#define A_MARK_BASELINE_ALPHA   (4U)
#define A_MARK_JUMP_TOTAL       (1U)
#define A_MARK_JUMP_SPAN        (1U)
#define A_MARK_DEBUG_PERIOD_MS  (1000U)

#define BUTTON_REARM_MS         (200U)
#define OLED_RUNTIME_ENABLE     (1)
#define CONTROL_LAG_WARN_MS     (60U)
#define CONTROL_LAG_DEBUG_ENABLE (0)

#define LEFT_MOTOR_INVERT       (0)
#define RIGHT_MOTOR_INVERT      (0)
#define LEFT_ENCODER_INVERT     (0)
#define RIGHT_ENCODER_INVERT    (0)

#define STEPPER_STEP_DEG        (0.05625f)
#define STEPPER_MIN_STEPS       (340)
#define STEPPER_NEUTRAL_LOW_STEPS  (610)
#define STEPPER_NEUTRAL_HIGH_STEPS (700)
#define STEPPER_NEUTRAL_STEPS   (655)
#define STEPPER_MAX_STEPS       (970)
#define STEPPER_STEPS_PER_PIPE_DEG (80.0f)
#define STEPPER_DEFAULT_DPS     (90.0f)
#define STEPPER_MAX_DPS         (240.0f)
#define STEPPER_MIN_PERIOD      (800U)
#define STEPPER_JOG_STEPS       (10)
#define STEPPER_JOG_INTERVAL_MS (80U)

#define K230_BALL_TIMEOUT_MS    (180U)
#define K230_BALL_MIN_CONF      (40)

#define BALL_CTRL_PERIOD_MS     (20U)
#define BALL_TARGET_PLUS_MM     (50.0f)
#define BALL_TARGET_MINUS_MM    (-50.0f)
#define BALL_SETTLE_ERR_MM      (8.0f)
#define BALL_SETTLE_SPEED_MM_S  (25.0f)
#define BALL_SETTLE_TICKS       (25U)
#define BALL_POS_KP             (2.0f)
#define BALL_POS_KD             (0.20f)
#define BALL_POS_MAX_SPEED      (140.0f)
#define BALL_SPEED_KP           (0.045f)
#define BALL_SPEED_KI           (0.0008f)
#define BALL_SPEED_MAX_THETA    (5.5f)
#define BALL_THETA_RATE_DEG     (90.0f)

#endif
