#ifndef APP_CONFIG_H
#define APP_CONFIG_H

#include <stdint.h>

#define MOTOR_PWM_PERIOD        (1600U)
#define MOTOR_PWM_DEAD_TICKS    (20U)
#define SPEED_CTRL_PERIOD_MS    (20U)
#define UART_REPORT_PERIOD_MS   (100U)
#define PWM_STEP_LIMIT          (30)
#define STARTUP_SAFE_MS         (800U)

#define DEFAULT_TARGET_COUNTS   (120.0f)
#define DEFAULT_KP              (1.20f)
#define DEFAULT_KI              (0.003f)
#define DEFAULT_KD              (0.0f)
#define DEFAULT_MAX_OUTPUT      (390.0f)
#define DEFAULT_MAX_INTEGRAL    (270.0f)

#define DEFAULT_LEFT_PWM_TRIM   (0)
#define DEFAULT_RIGHT_PWM_TRIM  (-14)
#define DEFAULT_BRAKE_MS        (120U)

#define LINE_DEFAULT_KP         (3.80f)
#define LINE_DEFAULT_KD         (2.40f)
#define LINE_DEFAULT_TARGET     (190.0f)
#define LINE_DEFAULT_BASE_PWM   (400)
#define LINE_CORR_LIMIT         (460)
#define LINE_MIN_WHEEL_TARGET   (25.0f)
#define LINE_SEARCH_PWM         (0)
#define LINE_CORRECTION_SIGN    (1)
#define LINE_CURVE_ERR_START    (14)
#define LINE_CURVE_TARGET_DROP  (55.0f)

#define Q4_AB_TARGET_TIME_MS     (7000U)
/* 模式二先越过电机死区，再在 2.5s 内从 200 线性增加到 400。 */
#define Q4_ACCEL_TIME_MS         (2500U)
#define Q4_CRUISE_TARGET_COUNTS  (150.0f)
#define Q4_START_PWM             (200)
#define Q4_CRUISE_BASE_PWM       (400)
/* 与模式一相同的启动变化率，使输出约 140ms 到达起步 PWM。 */
#define Q4_PWM_STEP_LIMIT        (30)
#define Q4_LINE_PWM_LIMIT        (180)
#define Q4_LEFT_PWM_TRIM         (0)
#define Q4_RIGHT_PWM_TRIM        (-14)
#define Q4_BRAKE_MS              (120U)
#define Q4_LINE_KP               (5.20f)
#define Q4_LINE_KD               (3.00f)
#define Q4_LINE_CORR_LIMIT       (240)
#define Q4_LINE_SEARCH_PWM       (0)
#define Q4_LINE_CURVE_ERR_START  (15)
#define Q4_LINE_CURVE_PWM_DROP   (70)
#define Q4_LINE_CURVE_TARGET_DROP (70.0f)
#define Q4_BALL_TARGET_MM        (0.0f)
#define Q4_EST_CRUISE_SPEED_MPS  (0.248f)
#define Q4_GRAVITY_MPS2          (9.80665f)
#define Q4_MAX_FEEDFORWARD_DEG   (3.0f)
/*
 * 编码器首次确认车轮已经运动后立即介入，并在 60ms 内快速渐入。
 * 这样补偿与实车起步接近同步，同时避免直接给水管角度阶跃。
 */
#define Q4_FEEDFORWARD_ENABLE    (1)
#define Q4_INITIAL_ANGLE_DEG     (1.70f)
/* 启动时固定保持明确的目标倾角；到时直接交给稳定版 PID，不做渐退。 */
#define Q4_INITIAL_ANGLE_HOLD_MS (200U)
#define Q4_PRELOAD_LEAD_MS       (200U)
#define Q4_INITIAL_ANGLE_RATE_DEG_S (240.0f)
/* 实机确认原移动补偿方向相反：仅翻转加速度前馈，不翻转球位置反馈。 */
#define Q4_FEEDFORWARD_SIGN      (1.0f)
#define Q4_ENCODER_METERS_PER_COUNT (0.00003333f)
#define Q4_ACCEL_LIMIT_MPS2      (0.45f)
#define Q4_MEASURED_ACCEL_WEIGHT (0.80f)
#define Q4_MOVING_SPEED_CPS      (50)

/* 模式二中心保持专用位置 PID；不影响模式一和要求3。 */
#define Q4_BALL_POS_KP           (0.080f)
#define Q4_BALL_POS_KI           (0.004f)
#define Q4_BALL_POS_KD           (0.000f)
#define Q4_BALL_POS_WEIGHT       (0.65f)
#define Q4_BALL_SPEED_KP         (0.050f)
#define Q4_BALL_SPEED_KI         (0.002f)
#define Q4_BALL_SPEED_KD         (0.00020f)
#define Q4_BALL_SPEED_WEIGHT     (0.35f)
#define Q4_BALL_PID_DEADBAND_MM  (2.0f)
#define Q4_BALL_PID_INT_LIMIT    (80.0f)
#define Q4_BALL_SPEED_INT_LIMIT  (100.0f)
#define Q4_BALL_ACCEL_LIMIT_MM_S2 (1200.0f)
#define Q4_BALL_MEDIAN_DELAY_FRAMES (1U)
#define Q4_BALL_ACTUATOR_LOOKAHEAD_MS (20U)
#define Q4_BALL_LOOKAHEAD_MAX_MS (120U)
#define Q4_BALL_PREDICT_POS_MAX_MM (18.0f)
#define Q4_BALL_PREDICT_SPEED_DELTA_MAX (80.0f)
#define Q4_BALL_POSITION_FILTER_NEW (0.45f)
#define Q4_BALL_VELOCITY_FILTER_NEW (0.50f)
#define Q4_BALL_ACCEL_FILTER_NEW (0.25f)
#define Q4_BALL_POS_OUT_MAX_DEG  (2.0f)
#define Q4_BALL_SPEED_OUT_MAX_DEG (1.5f)
#define Q4_BALL_PID_MAX_THETA    (1.8f)

#define A_MARK_DEFAULT_TOTAL    (3U)
#define A_MARK_DEFAULT_SPAN     (3U)
#define A_MARK_DEFAULT_FRAMES   (2U)
#define A_MARK_FINISH_TOTAL     (3U)
#define A_MARK_FINISH_SPAN      (3U)
#define A_MARK_RELEASE_FRAMES   (4U)
#define A_MARK_MIN_LAP_MS       (5000U)
#define A_MARK_MIN_LAP_COUNTS   (9000U)
#define A_MARK_BASELINE_ALPHA   (4U)
#define A_MARK_JUMP_TOTAL       (1U)
#define A_MARK_JUMP_SPAN        (1U)
#define A_MARK_DEBUG_PERIOD_MS  (1000U)

#define BUTTON_REARM_MS         (200U)
#define OLED_RUNTIME_ENABLE     (1)
#define CONTROL_LAG_WARN_MS     (60U)
#define CONTROL_LAG_DEBUG_ENABLE (0)

#define LEFT_MOTOR_INVERT       (0)
#define RIGHT_MOTOR_INVERT      (0)
#define LEFT_ENCODER_INVERT     (0)
#define RIGHT_ENCODER_INVERT    (0)

/* X42S TTL 串口绝对位置控制参数，默认配合 X 固件使用。 */
#define X42S_ADDRESS            (1U)
#define X42S_STARTUP_DELAY_MS   (800U)
#define X42S_COMMAND_PERIOD_MS  (20U)
#define X42S_POSITION_POLL_MS   (100U)
#define X42S_STATUS_POLL_MS     (500U)
#define X42S_RX_TIMEOUT_MS      (300U)
#define X42S_POSITION_UNITS_PER_DEG (100.0f)
#define X42S_MOTOR_DEG_PER_PIPE_DEG (4.5f)
#define X42S_MAX_MOTOR_ANGLE_DEG (28.0f)
#define X42S_POSITION_TOLERANCE_DEG (0.20f)
#define STEPPER_DEFAULT_DPS     (90.0f)
#define STEPPER_MAX_DPS         (240.0f)
#define STEPPER_JOG_STEPS       (5)
#define STEPPER_JOG_INTERVAL_MS (80U)

#define K230_BALL_TIMEOUT_MS    (350U)
#define K230_BALL_MIN_CONF      (40)
#define K230_STATUS_PERIOD_MS   (100U)

#define BALL_CTRL_PERIOD_MS     (20U)
#define BALL_TARGET_PLUS_MM     (50.0f)
#define BALL_TARGET_MINUS_MM    (-50.0f)
#define BALL_SETTLE_ERR_MM      (8.0f)
#define BALL_SETTLE_SPEED_MM_S  (25.0f)
#define BALL_SETTLE_TICKS       (25U)
#define BALL_POS_KP             (2.0f)
#define BALL_POS_KD             (0.20f)
#define BALL_POS_MAX_SPEED      (140.0f)
#define BALL_SPEED_KP           (0.045f)
#define BALL_SPEED_KI           (0.040f)
#define BALL_SPEED_INT_MAX      (60.0f)
#define BALL_SPEED_MAX_THETA    (5.5f)
#define BALL_THETA_RATE_DEG     (90.0f)
#define BALL_ACTUATOR_ANGLE_SIGN (1.0f)

#endif
